/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var checkType = kurentoClient.checkType;
var ChecktypeError = checkType.ChecktypeError;

var ComplexType = kurentoClient.register.complexTypes.ComplexType;


/**
 * AR Key-Value-Pair of Strings and integers for passing data
 *
 * @constructor module:armarkerdetector/complexTypes.ArKvpInteger
 *
 * @property {external:String} key
 *  unique key for a value
 * @property {external:Integer} value
 *  arbitrary value
 */
function ArKvpInteger(arKvpIntegerDict){
  if(!(this instanceof ArKvpInteger))
    return new ArKvpInteger(arKvpIntegerDict)

  arKvpIntegerDict = arKvpIntegerDict || {}

  // Check arKvpIntegerDict has the required fields
  checkType('String', 'arKvpIntegerDict.key', arKvpIntegerDict.key, {required: true});
  checkType('int', 'arKvpIntegerDict.value', arKvpIntegerDict.value, {required: true});

  // Init parent class
  ArKvpInteger.super_.call(this, arKvpIntegerDict)

  // Set object properties
  Object.defineProperties(this, {
    key: {
      writable: true,
      enumerable: true,
      value: arKvpIntegerDict.key
    },
    value: {
      writable: true,
      enumerable: true,
      value: arKvpIntegerDict.value
    }
  })
}
inherits(ArKvpInteger, ComplexType)

// Private identifiers to allow re-construction of the complexType on the server
// They need to be enumerable so JSON.stringify() can access to them
Object.defineProperties(ArKvpInteger.prototype, {
  __module__: {
    enumerable: true,
    value: "armarkerdetector"
  },
  __type__: {
    enumerable: true,
    value: "ArKvpInteger"
  }
})

/**
 * Checker for {@link module:armarkerdetector/complexTypes.ArKvpInteger}
 *
 * @memberof module:armarkerdetector/complexTypes
 *
 * @param {external:String} key
 * @param {module:armarkerdetector/complexTypes.ArKvpInteger} value
 */
function checkArKvpInteger(key, value)
{
  if(!(value instanceof ArKvpInteger))
    throw ChecktypeError(key, ArKvpInteger, value);
};


module.exports = ArKvpInteger;

ArKvpInteger.check = checkArKvpInteger;
