/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

/**
 * Media API for the Kurento Web SDK
 *
 * @module armarkerdetector/complexTypes
 *
 * @copyright 2013-2015 Kurento (http://kurento.org/)
 * @license LGPL
 */

var ArKvpFloat = require('./ArKvpFloat');
var ArKvpInteger = require('./ArKvpInteger');
var ArKvpString = require('./ArKvpString');
var ArMarkerPose = require('./ArMarkerPose');
var ArThing = require('./ArThing');
var OverlayType = require('./OverlayType');


exports.ArKvpFloat = ArKvpFloat;
exports.ArKvpInteger = ArKvpInteger;
exports.ArKvpString = ArKvpString;
exports.ArMarkerPose = ArMarkerPose;
exports.ArThing = ArThing;
exports.OverlayType = OverlayType;
